name: Solver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solver

    steps:
    - uses: actions/checkout@v4
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run unsafe tests
      run: cargo miri test miri_
